# Tensorflow 기초

## 상수와 변수 Constant ans Variable

In [1]:
import tensorflow as tf

2022-11-28 16:54:16.276042: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-28 16:54:16.370610: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-11-28 16:54:16.789695: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda-11.3/lib64
2022-11-28 16:54:16.789736: W tensorflow/compiler/xla/strea

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
# 리스트 형을 텐서로 int!!

li_ten = tf.constant([1, 2, 3])
li_ten

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [5]:
## 이번에는 Float 형 텐서로!!

li_ten_f = tf.constant([1., 2., 3.])
li_ten_f

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [6]:
## 이번에는 튜플을 텐서로!!

tu_ten = tf.constant(((1, 2, 3), (1, 2, 3)))
tu_ten

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [7]:
## 넘파이를 텐서로 가능!!

import numpy as np

arr = np.array([1., 2., 3.])
arr_ten = tf.constant(arr)
arr_ten

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [8]:
## 텐서를 넘파이로!!

arr_ten.numpy(), type(arr_ten.numpy())

(array([1., 2., 3.]), numpy.ndarray)

In [9]:
## shape 이나 dtype을 확인하기

li_ten.shape, tu_ten.shape

(TensorShape([3]), TensorShape([2, 3]))

In [10]:
arr_ten.dtype, li_ten.dtype

(tf.float64, tf.int32)

In [11]:
## 방금처럼 텐서로 지정하거나 

tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [14]:
## cast를 사용하여 형 변환이 가능

tf.cast(tensor, dtype=tf.int16)

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 2, 3], dtype=int16)>

In [15]:
# 1로 채우는 텐서도 만들 수 있따.

tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [16]:
tf.zeros((2, 5), dtype="int32")

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [17]:
## 텐서플로우에도 Range가 가능하다!!

tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [18]:
tf.range(1, 11)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

### 텐서로 등비수열 만들기!!
> __참고로 빠른 동작을 위해서는 반복문을 최대한 지양하는 것이 좋다__

In [21]:
def geometric_sequence(n):
    r = tf.range(n, dtype='int32')
    s = tf.ones(n, dtype=tf.int32)* 2
    return s**r

In [22]:
# 위 코딩 기법은 굉장히 중요!!

print(geometric_sequence(10))

tf.Tensor([  1   2   4   8  16  32  64 128 256 512], shape=(10,), dtype=int32)


In [23]:
## 랜덤 만들기!!

shape = (3, 3)
tf.random.normal(shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.17091158,  0.08330786,  0.7003735 ],
       [ 0.27586544, -1.6199648 , -1.7641399 ],
       [-0.6069905 , -0.30424544, -0.13784763]], dtype=float32)>

In [24]:
## 텐서플로우에서 랜덤 시드 관리하기!!

tf.random.set_seed(13)
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep='\n')

tf.Tensor([0.5983684], shape=(1,), dtype=float32)
tf.Tensor([0.53933334], shape=(1,), dtype=float32)


In [26]:
## 랜덤시드를 안넣으니 다른 랜덤한 값이 나온다!!

a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep='\n')

tf.Tensor([0.27229798], shape=(1,), dtype=float32)
tf.Tensor([0.5121772], shape=(1,), dtype=float32)


In [27]:
## 시드 설정을 사용하는 이유

tf.random.set_seed(13)
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep='\n')

tf.Tensor([0.5983684], shape=(1,), dtype=float32)
tf.Tensor([0.53933334], shape=(1,), dtype=float32)


## Variable 
### 변수로 선언하기

In [29]:
tensor = tf.constant([[1., 2.], [3., 4.]])
arr = np.array([[1, 2], [3, 4]])
li = [[1,2], [3, 4]]

te_var = tf.Variable(tensor)
arr_var = tf.Variable(arr)
li_var = tf.Variable(li)

print(te_var)
print(arr_var)
print(li_var)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>


In [31]:
print("Shape :", te_var.shape)
print('---')
print("DType :", te_var.dtype)
print('---')
print("As Numpy :", te_var.numpy)

Shape : (2, 2)
---
DType : <dtype: 'float32'>
---
As Numpy : <bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>>


In [32]:
## 메모리를 허비 하지  않고 재할당을 해보자!!

a = tf.Variable([2., 3.])
print("First :", a, "\n")

a.assign([1, 2])
print("Second :", a, "\n")


First : <tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)> 

Second : <tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)> 



### 텐서 연산

In [33]:
a = tf.range(6, dtype=tf.int32)
b = 2 * tf.ones(6, dtype=tf.int32)

In [34]:
tf.add(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7], dtype=int32)>

In [35]:
a+ b

# 위 두개가 사실은 같다

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7], dtype=int32)>

In [38]:
# 최대값 
tf.maximum(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5], dtype=int32)>

In [39]:
# 연습용 텐서 제작

rank_2 = tf.random.normal((3, 3))
rank_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.9487271 ,  1.3044667 , -1.1531729 ],
       [-0.28560743,  0.48564127, -0.9099395 ],
       [-0.96096003,  1.3391656 , -0.11258006]], dtype=float32)>

In [40]:
rank_2[0]

# 첫번째 행

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.9487271,  1.3044667, -1.1531729], dtype=float32)>

In [41]:
rank_2[0, 0]

# 첫번째 열, 첫번째 행


<tf.Tensor: shape=(), dtype=float32, numpy=-0.9487271>

In [42]:
## 3차원짜리 텐서 제작

ranl_3 = tf.random.normal((3, 3, 3))
ranl_3

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-0.1856016 , -1.1418061 ,  0.0194767 ],
        [-2.7855177 ,  1.2621061 , -1.2295452 ],
        [-0.9714309 , -0.35085803,  1.1138306 ]],

       [[ 0.9682026 , -1.9595007 ,  1.0642354 ],
        [ 1.494038  , -1.1601017 ,  1.4813476 ],
        [-0.21271256,  1.0881292 ,  0.31397238]],

       [[-0.52992046,  0.19140598, -0.2779634 ],
        [-1.2172662 ,  0.5619219 , -2.132913  ],
        [ 0.8605408 ,  0.65008086,  0.33721906]]], dtype=float32)>

In [43]:
### 4차원짜리 텐서 

rank_4 = tf.random.normal((3, 3, 3, 3))
rank_4

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[ 1.3927455 , -0.45965314,  0.49407616],
         [ 0.17237075,  0.93350935,  1.6913122 ],
         [ 0.91713065, -0.16278401,  0.3994191 ]],

        [[ 1.3299477 , -0.16608767,  0.52453625],
         [-0.825861  , -0.39364755,  0.15490197],
         [-0.7261836 , -0.21677208,  0.14307553]],

        [[-0.7616838 , -1.7694571 , -1.2084615 ],
         [ 0.15294294,  0.61789715,  0.75220877],
         [-0.9087012 ,  0.34433067, -0.1459559 ]]],


       [[[ 2.2195857 , -0.9483894 , -0.72741896],
         [-0.09788546, -0.74635005,  1.6196522 ],
         [-1.339364  ,  0.10365214,  1.5238657 ]],

        [[ 1.970443  , -1.9742427 ,  1.646089  ],
         [-0.10265194, -0.14842309,  0.6076201 ],
         [ 0.31007034, -0.16753197, -0.6445421 ]],

        [[-0.11728214, -0.38824674,  0.31977358],
         [-0.8027508 , -1.8807936 ,  0.35686776],
         [-1.498092  , -1.8625052 ,  1.2523474 ]]],


       [[[ 1.9372497 , -1.0422

In [44]:
## 행렬 곱

a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
b = tf.constant([[1, 1], [1, 1]], dtype=tf.float32)
tf.matmul(a, b)

2022-11-28 17:27:37.021568: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:630] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [1., 1.]], dtype=float32)>

In [45]:
## 역행렬
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
tf.linalg.inv(a)

2022-11-28 17:28:17.018652: I tensorflow/core/util/cuda_solvers.cc:179] Creating GpuSolver handles for stream 0x7682ff0


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5, 0. ],
       [0. , 1. ]], dtype=float32)>

In [46]:
## 테스트용 제작

a = tf.range(6, dtype=tf.int32)
print("a    :", a, '\n')

a    : tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32) 



In [47]:
## 행렬의 크기 변경

a_2d = tf.reshape(a, (2, 3))
print("a     :", a)
print("a_2d  :", a_2d, "\n")

a     : tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32)
a_2d  : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32) 



In [48]:
## 전치

a_2d_t = tf.transpose(a_2d)
print("a_2d   :", a_2d)
print("a_2d_t :", a_2d_t, "\n")

a_2d   : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)
a_2d_t : tf.Tensor(
[[0 3]
 [1 4]
 [2 5]], shape=(3, 2), dtype=int32) 



In [49]:
## 첫번째 차원 늘리기

a_3d = tf.expand_dims(a_2d, 0)
print("a_2d   :", a_2d)
print("a_3d   :", a_3d, '\n')

a_2d   : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)
a_3d   : tf.Tensor(
[[[0 1 2]
  [3 4 5]]], shape=(1, 2, 3), dtype=int32) 



In [50]:
# 마지막 차원 늘리기

a_4d = tf.expand_dims(a_3d, 3)
print("a_3d   :", a_3d)
print("a_4d   :", a_4d, '\n')

a_3d   : tf.Tensor(
[[[0 1 2]
  [3 4 5]]], shape=(1, 2, 3), dtype=int32)
a_4d   : tf.Tensor(
[[[[0]
   [1]
   [2]]

  [[3]
   [4]
   [5]]]], shape=(1, 2, 3, 1), dtype=int32) 



In [51]:
### 차원의 크기가 1인 것 정리하기!!!
### 생각보다 자주 쓰이는 함수이니 기억해놓자

a_1d = tf.squeeze(a_4d)
print("a_4d   :", a_4d)
print("a_1d   :", a_1d, '\n')

a_4d   : tf.Tensor(
[[[[0]
   [1]
   [2]]

  [[3]
   [4]
   [5]]]], shape=(1, 2, 3, 1), dtype=int32)
a_1d   : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32) 



In [52]:
## 다시 연습용 텐서 제작

a = tf.reshape(tf.range(12), (3, 4))
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [53]:
tf.slice(a, [0, 1], [2, 3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]], dtype=int32)>

In [54]:
## 가로축을 따라 2개로 분리

a1, a2 = tf.split(a, num_or_size_splits=2, axis=1)
print(a1)
print(a2)

tf.Tensor(
[[0 1]
 [4 5]
 [8 9]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  3]
 [ 6  7]
 [10 11]], shape=(3, 2), dtype=int32)


In [55]:
tf.concat([a1, a2], 1)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [56]:
### 가로축 따로 세 개로 확대

tf.tile(a1, [1, 3])   # 가로축 (axis=1)을 따라 3개로 복사 붙이기

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 0, 1, 0, 1],
       [4, 5, 4, 5, 4, 5],
       [8, 9, 8, 9, 8, 9]], dtype=int32)>

In [57]:
## 스택은 차원을 늘리면서 허ㅏㅂ치기

# 3X2 행렬 a1, a2를 추가적인 차원으로 붙여서 2x3x2 고차원 텐서 생성

a3 = tf.stack([a1, a2])
a3

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]], dtype=int32)>